# Generated by Django 4.2.8 on 2024-05-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
