# Generated by Django 4.2.8 on 2024-06-02 09:20

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='')),
                ('country', models.CharField(max_length=255, verbose_name='')),
                ('city', models.CharField(max_length=255, verbose_name='')),
                ('address', models.TextField(max_length=1000, verbose_name='')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('creator', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-date_register'],
                'indexes': [models.Index(fields=['date_register'], name='task_manage_date_re_034f70_idx')],
            },
        ),
    ]
