# Generated by Django 4.2.8 on 2024-06-20 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_user', '0002_profile_verify_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('member', 'Участник')], max_length=10, verbose_name='Роль')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('incative', 'Не активен')], max_length=10, verbose_name='Статус')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.TextField(max_length=1000, verbose_name='Адрес')),
                ('date_register', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('creator', models.ForeignKey(default='auth.User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-date_register'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('code', models.CharField(default='Code00000', max_length=255, verbose_name='Код')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('member', models.ManyToManyField(blank=True, related_name='projects', to='task_manager.member', verbose_name='Участник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='task_manager.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='task_manager.organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='profile_user.profile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='members', to='task_manager.project', verbose_name='Проект'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['date_created'], name='task_manage_date_cr_2704ff_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['date_register'], name='task_manage_date_re_034f70_idx'),
        ),
    ]
