# Generated by Django 4.2.8 on 2024-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('member', 'Участник'), ('admin', 'Администратор'), ('owner', 'Создатель')], max_length=10, verbose_name='Роль'),
        ),
    ]
